name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
# Setup: optimization
  project-setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.13

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3
        echo "$HOME/local/bin" >> $GITHUB_PATH

    - name: Save Poetry Path
      run: echo "POETRY_PATH=$HOME/.local/bin/poetry" >> $GITHUB_ENV

  docker-build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Build Docker Image
      run: docker build -t docker-python-poetry .

  app-build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Install app dependencies
      run: poetry install

  security-check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Run Security Check
      run: |
        poetry install --only=security
        poetry run bandit -r .
